# Generated by Django 5.2.6 on 2025-10-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom ou description du produit', max_length=200, verbose_name='Nom du produit')),
                ('category', models.CharField(choices=[('ALIMENTAIRE', 'Alimentaire'), ('HYGIENE', 'Hygiene'), ('VETEMENT', 'Vetement'), ('MOBILIER', 'Mobilier'), ('SCOLAIRE', 'Scolaire'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Categorie')),
                ('quantity', models.IntegerField(default=0, help_text='Quantite actuelle disponible', verbose_name='Quantite en stock')),
                ('unit', models.CharField(default='unite', help_text='Ex: unite, kg, litre, boite, etc.', max_length=50, verbose_name='Unite de mesure')),
                ('description', models.TextField(blank=True, help_text='Details supplementaires sur le produit', null=True, verbose_name='Description')),
                ('min_threshold', models.IntegerField(default=0, help_text='Alerte si la quantite descend en dessous de cette valeur', verbose_name='Seuil minimum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['category', 'name'],
            },
        ),
    ]
