version: '3.8'

services:
  app:
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=rosa.settings
      - DEBUG=True
    command:
      - /bin/bash
      - -c
      - |
        wait-for postgres:5432 -- echo 'Postgres Ready'
        python manage.py collectstatic --noinput
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/usr/src/app
      - rosa-static-files:/usr/src/app/static_collected
      - rosa-media-files:/usr/src/app/media
    ports:
      - "${APP_PORT:-9000}:9000"
