# Generated by Django 5.2.6 on 2025-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('news_type', models.CharField(choices=[('EVENEMENT', 'Événement'), ('PARTENARIAT', 'Partenariat'), ('FORMATION', 'Formation'), ('INFO', 'Information'), ('AUTRE', 'Autre')], default='INFO', max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Date de publication')),
                ('is_pinned', models.BooleanField(default=False, help_text='Afficher en premier', verbose_name='Épinglé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-is_pinned', '-publication_date', '-created_at'],
            },
        ),
    ]
