# Generated by Django 5.2.6 on 2025-09-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[('M', 'M.'), ('MME', 'Mme'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Civilité')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse de domiciliation')),
                ('residence_address', models.TextField(blank=True, verbose_name='Lieu de résidence')),
                ('occupation', models.CharField(blank=True, max_length=200, verbose_name='Métier / Savoir-faire')),
                ('housing_status', models.CharField(blank=True, choices=[('CADA', 'CADA'), ('CAO', 'CAO'), ('CHRS', 'CHRS'), ('DIFFUS', 'Logement Diffus'), ('COLLECTIF', 'Collectif'), ('QPV', 'Quartier QPV'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Hébergement')),
                ('family_status', models.CharField(choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('VEUF', 'Veuf/Veuve'), ('VIE_MARITALE', 'Vie maritale'), ('DIVORCE', 'Divorcé(e)'), ('SEPARE', 'Séparé(e)')], default='CELIBATAIRE', max_length=20, verbose_name='Situation Familiale')),
                ('dependents_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants à charge")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date du snapshot')),
                ('rsa_prime_activite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="RSA/Prime d'activité")),
                ('aah_pension_invalidite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="AAH, PI (pension d'invalidité)")),
                ('apl', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='APL (Bailleur ou bénéficiaire)')),
                ('paje', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PAJE')),
                ('af', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='AF (Allocations Familiales)')),
                ('cf', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CF (Complément Familial)')),
                ('asf', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ASF (Allocation de Soutien Familial)')),
                ('ape_conge_parental', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='APE Congé Parental')),
                ('ij_cpam_msa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IJ CPAM/MSA')),
                ('france_travail', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='France Travail')),
                ('retraite_aspa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retraite, A.S.P.A.')),
                ('salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salaire')),
                ('ada', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Allocation Demandeur d'Asile (ADA)")),
                ('stage_formation_bourses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stage, Formation, bourses')),
                ('autres_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres revenus')),
                ('aide_conseil_departemental', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aide Conseil Départemental')),
                ('pension_alimentaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pension alimentaire')),
                ('travail_non_declare', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Travail non déclaré')),
                ('soutien_familial_amical', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Soutien familial ou amical')),
                ('contrat_garantie_jeunes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Contrat Garantie Jeunes (MLJ)')),
                ('contrat_apprentissage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Contrat d'apprentissage")),
                ('tickets_service', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tickets service')),
                ('bons_alimentation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Bons d'alimentation")),
                ('loyer_residuel', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Loyer résiduel')),
                ('energie', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Énergie')),
                ('eau', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Eau')),
                ('assurance_habitation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Assurance habitation')),
                ('mutuelle_privee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mutuelle privée')),
                ('css', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='CSS (Complémentaire Santé Solidaire)')),
                ('frais_scolaires', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais scolaires (cantine, sorties)')),
                ('frais_sante_non_rembourses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais de santé non remboursés')),
                ('transport_commun', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Transport en commun')),
                ('carburant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Carburant')),
                ('credit_consommation', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Crédit à la consommation')),
                ('dettes_diverses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Dettes diverses')),
                ('abonnements_sport_culture', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Abonnements sport et culture')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='beneficiaries.beneficiary', verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Snapshot Financier',
                'verbose_name_plural': 'Snapshots Financiers',
                'ordering': ['-date'],
            },
        ),
    ]
