# Generated by Django 5.2.6 on 2025-09-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsnapshot',
            name='rsa_prime_activite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="RSA/Prime d'activité"),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('observations', models.TextField(blank=True, help_text="Notes sur l'enfant", verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='beneficiaries.beneficiary', verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Enfant',
                'verbose_name_plural': 'Enfants',
                'ordering': ['birth_date'],
            },
        ),
    ]
