# Generated by Django 5.2.6 on 2025-09-26 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_alter_financialsnapshot_rsa_prime_activite_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('ASSOCIATION', "Entretien à l'association"), ('EXTERNAL', 'Entretien externe'), ('PHONE', 'Entretien téléphonique'), ('HOME_VISIT', 'Visite à domicile'), ('EMAIL', 'Contact par email'), ('OTHER', 'Autre')], default='ASSOCIATION', max_length=20, verbose_name="Type d'interaction")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('changes_made', models.TextField(blank=True, help_text='Décrivez les actions, services activés, modifications apportées', verbose_name='Changements apportés')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Cette interaction nécessite-t-elle un suivi ?', verbose_name='Suivi requis')),
                ('follow_up_date', models.DateField(blank=True, help_text='Date prévue pour le suivi', null=True, verbose_name='Date de suivi')),
                ('follow_up_notes', models.TextField(blank=True, help_text='Notes concernant le suivi à effectuer', verbose_name='Notes de suivi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'interaction")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='beneficiaries.beneficiary', verbose_name='Bénéficiaire')),
                ('financial_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction', to='beneficiaries.financialsnapshot', verbose_name='Snapshot financier associé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
