# Generated by Django 5.2.6 on 2025-09-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0003_interaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialsnapshot',
            options={'ordering': ['-date'], 'verbose_name': 'Photo Instantanée Financière', 'verbose_name_plural': 'Photos Instantanées Financières'},
        ),
        migrations.AlterField(
            model_name='financialsnapshot',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de la photo instantanée'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='financial_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction', to='beneficiaries.financialsnapshot', verbose_name='Photo instantanée financière associée'),
        ),
    ]
