# Generated by Django 5.2.6 on 2025-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_alter_financialsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='civility',
            field=models.CharField(blank=True, choices=[('M', 'M.'), ('MME', 'Mme'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Civilité'),
        ),
    ]
