# Generated by Django 5.2.6 on 2025-10-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0006_alter_interaction_user'),
        ('volunteers', '0003_delete_timetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='preferred_contact',
            field=models.ForeignKey(blank=True, help_text='Bénévole référent pour ce bénéficiaire', limit_choices_to={'role__in': ['ADMIN', 'EMPLOYEE', 'VOLUNTEER_INTERVIEW']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_beneficiaries', to='volunteers.volunteer', verbose_name='Interlocuteur privilégié'),
        ),
    ]
