# Generated by Django 5.2.6 on 2025-10-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0007_beneficiary_preferred_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='nationality',
            field=models.CharField(blank=True, choices=[('FRANCAISE', 'Française'), ('UE', 'Union Européenne'), ('NON_UE', 'Hors Union Européenne')], max_length=20, verbose_name='Nationalité'),
        ),
    ]
