# Generated by Django 5.2.6 on 2025-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0008_beneficiary_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='La personne consent au recueil et au traitement de ses données personnelles', verbose_name='Consentement RGPD'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gdpr_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de consentement RGPD'),
        ),
    ]
