# Generated by Django 5.2.6 on 2025-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0009_beneficiary_gdpr_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Par qui le bénéficiaire a été adressé (ex: Croix-Rouge, assistant social, bouche à oreille, etc.)', max_length=200, verbose_name='Adressé par'),
        ),
    ]
