# Generated by Django 5.2.7 on 2025-10-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0010_beneficiary_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='alert_level',
            field=models.CharField(choices=[('VERT', 'Situation normale'), ('ORANGE', 'Surveillance nécessaire'), ('ROUGE', 'Situation critique/urgente')], default='VERT', help_text="Niveau d'urgence ou de gravité de la situation", max_length=10, verbose_name="Niveau d'alerte"),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='profile_tag',
            field=models.CharField(blank=True, choices=[('', '--------'), ('FEMME_SEULE_ENFANTS', 'Femme seule avec enfant(s)'), ('ETUDIANT', 'Étudiant'), ('RETRAITE', 'Retraité'), ('PERSONNE_SEULE', 'Personne seule'), ('FAMILLE_NOMBREUSE', 'Famille nombreuse')], help_text='Identifier un profil particulier nécessitant une attention spécifique', max_length=30, verbose_name='Profil spécifique'),
        ),
    ]
