# Generated by Django 5.2.6 on 2026-03-22 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0011_beneficiary_alert_level_beneficiary_profile_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='file_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° de dossier'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='first_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de première entrée'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='housing_status_other',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hébergement (précision)'),
        ),
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Fille'), ('G', 'Garçon')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='financialsnapshot',
            name='telephonie_internet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Téléphonie / Internet'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='financial_aid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant du secours financier'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='financial_aid_details',
            field=models.CharField(blank=True, max_length=300, verbose_name='Spécification du secours'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='primary_need',
            field=models.CharField(blank=True, choices=[('', '--------'), ('ALIMENTAIRE', 'Alimentaire'), ('VESTIMENTAIRE', 'Vestimentaire'), ('FINANCIER', 'Financier'), ('ADMINISTRATIF', 'Administratif'), ('LOGEMENT', 'Logement'), ('SANTE', 'Santé'), ('EMPLOI', 'Emploi / Formation'), ('JURIDIQUE', 'Juridique'), ('ECOUTE', 'Écoute / Soutien moral'), ('AUTRE', 'Autre')], max_length=20, verbose_name='1er besoin exprimé'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='primary_need_details',
            field=models.TextField(blank=True, verbose_name='Précisez le besoin'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('IDENTITE', "Pièce d'identité"), ('DOMICILE', 'Justificatif de domicile'), ('REVENUS', 'Justificatif de revenus'), ('CAF', 'Attestation CAF'), ('SANTE', 'Document médical'), ('ADMINISTRATIF', 'Document administratif'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de document')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beneficiaries.beneficiary', verbose_name='Bénéficiaire')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploadé par')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
