# Generated by Django 5.2.6 on 2025-09-28 16:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(blank=True, choices=[('M', 'M.'), ('MME', 'Mme'), ('AUTRE', 'Autre')], max_length=10, verbose_name='Civilité')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('EMPLOYEE', 'Salarié'), ('VOLUNTEER_INTERVIEW', 'Bénévole Entretien'), ('VOLUNTEER_GOVERNANCE', 'Bénévole Gouvernance')], default='VOLUNTEER_INTERVIEW', help_text="Détermine les permissions d'accès dans l'application", max_length=30, verbose_name='Rôle')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('skills', models.TextField(blank=True, help_text='Compétences particulières du bénévole', verbose_name='Compétences/Savoir-faire')),
                ('availability', models.TextField(blank=True, help_text='Jours et heures de disponibilité', verbose_name='Disponibilités')),
                ('join_date', models.DateField(default=datetime.date.today, verbose_name="Date d'adhésion")),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Dernière activité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Bénévole',
                'verbose_name_plural': 'Bénévoles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Premier jour du mois concerné (ex: 2024-03-01 pour mars 2024)', verbose_name='Mois')),
                ('hours_worked', models.DecimalField(decimal_places=1, default=0, help_text="Nombre d'heures de bénévolat effectuées ce mois-ci", max_digits=5, verbose_name='Heures travaillées')),
                ('activities', models.TextField(blank=True, help_text='Description des activités menées ce mois-ci', verbose_name='Activités réalisées')),
                ('notes', models.TextField(blank=True, help_text='Observations particulières ou commentaires', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_trackings', to='volunteers.volunteer', verbose_name='Bénévole')),
            ],
            options={
                'verbose_name': "Suivi d'heures",
                'verbose_name_plural': "Suivis d'heures",
                'ordering': ['-month'],
                'unique_together': {('volunteer', 'month')},
            },
        ),
    ]
