# Generated by Django 5.2.6 on 2025-10-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='availability',
        ),
    ]
