# Generated by Django 5.2.6 on 2025-10-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_remove_volunteer_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeTracking',
        ),
    ]
