# Generated by Django 5.2.6 on 2025-09-28 20:20

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiaries', '0006_alter_interaction_user'),
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('day', 'Vue jour'), ('week', 'Vue semaine'), ('month', 'Vue mois')], default='week', max_length=10, verbose_name='Vue par défaut')),
                ('work_start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Début de journée')),
                ('work_end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='Fin de journée')),
                ('show_weekends', models.BooleanField(default=False, verbose_name='Afficher les week-ends')),
                ('email_reminders', models.BooleanField(default=True, verbose_name='Rappels par email')),
                ('reminder_hours_before', models.IntegerField(default=24, verbose_name='Rappel (heures avant)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('volunteer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='volunteers.volunteer', verbose_name='Bénévole')),
            ],
            options={
                'verbose_name': 'Calendrier bénévole',
                'verbose_name_plural': 'Calendriers bénévoles',
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('AVAILABILITY', 'Disponibilité'), ('BUSY', 'Occupé'), ('UNAVAILABLE', 'Indisponible')], default='AVAILABILITY', max_length=15, verbose_name='Type de créneau')),
                ('recurrence_type', models.CharField(choices=[('NONE', 'Ponctuel'), ('WEEKLY', 'Hebdomadaire'), ('BIWEEKLY', 'Toutes les 2 semaines'), ('MONTHLY', 'Mensuel')], default='WEEKLY', max_length=10, verbose_name='Type de récurrence')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], null=True, verbose_name='Jour de la semaine')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Date spécifique')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Valide à partir du')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Titre du créneau')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_bookable', models.BooleanField(default=True, verbose_name='Peut être réservé')),
                ('max_appointments', models.PositiveIntegerField(default=1, verbose_name='Nombre max de RDV')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_availability_slots', to=settings.AUTH_USER_MODEL)),
                ('volunteer_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='calendar_app.volunteercalendar')),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'verbose_name_plural': 'Créneaux de disponibilité',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Date du rendez-vous')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('appointment_type', models.CharField(choices=[('INTERVIEW', 'Entretien'), ('FOLLOW_UP', 'Suivi'), ('ADMINISTRATIVE', 'Aide administrative'), ('SOCIAL', 'Accompagnement social'), ('OTHER', 'Autre')], default='INTERVIEW', max_length=15, verbose_name='Type de rendez-vous')),
                ('title', models.CharField(max_length=200, verbose_name='Objet du rendez-vous')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('CONFIRMED', 'Confirmé'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], default='SCHEDULED', max_length=12, verbose_name='Statut')),
                ('preparation_notes', models.TextField(blank=True, verbose_name='Notes de préparation')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Notes de compte-rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='beneficiaries.beneficiary', verbose_name='Bénéficiaire')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('availability_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='calendar_app.availabilityslot', verbose_name='Créneau de disponibilité')),
                ('volunteer_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='calendar_app.volunteercalendar')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['appointment_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_date', models.DateField(verbose_name="Date d'exception")),
                ('exception_type', models.CharField(choices=[('CANCELLED', 'Annulé'), ('MODIFIED', 'Modifié'), ('MOVED', 'Déplacé')], max_length=10, verbose_name="Type d'exception")),
                ('new_start_time', models.TimeField(blank=True, null=True, verbose_name='Nouvelle heure de début')),
                ('new_end_time', models.TimeField(blank=True, null=True, verbose_name='Nouvelle heure de fin')),
                ('new_date', models.DateField(blank=True, null=True, verbose_name='Nouvelle date')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('availability_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar_app.availabilityslot')),
            ],
            options={
                'verbose_name': 'Exception de disponibilité',
                'verbose_name_plural': 'Exceptions de disponibilité',
                'unique_together': {('availability_slot', 'exception_date')},
            },
        ),
    ]
