# Generated by Django 5.2.6 on 2025-09-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Objet du rendez-vous'),
        ),
    ]
