# Generated by Django 5.2.6 on 2025-09-30 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='volunteer_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='calendar_app.volunteercalendar', verbose_name='Bénévole assigné'),
        ),
    ]
