# Generated by Django 5.2.6 on 2025-10-02 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, help_text='Laisser vide pour un don anonyme', max_length=255, null=True, verbose_name='Nom du donateur')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant du don en euros', max_digits=10, verbose_name='Montant')),
                ('payment_type', models.CharField(choices=[('CASH', 'Espèces'), ('TRANSFER', 'Virement bancaire'), ('CARD', 'Paiement par carte'), ('CHECK', 'Chèque')], max_length=20, verbose_name='Type de paiement')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du don')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Don anonyme')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur ce don', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Don manuel',
                'verbose_name_plural': 'Dons manuels',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
