# Generated by Django 5.2.6 on 2025-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description affichée sous le graphique', verbose_name='Description')),
                ('section', models.CharField(choices=[('IMPACT', 'Impact Social'), ('DEMOGRAPHIC', 'Démographie & Profils'), ('FINANCIAL', 'Données Financières'), ('OPERATIONAL', 'Opérationnel'), ('TRENDS', 'Tendances'), ('ADVANCED', 'Visualisations Avancées')], default='OPERATIONAL', help_text='Catégorie de classement du graphique', max_length=20, verbose_name='Section')),
                ('chart_type', models.CharField(choices=[('line', 'Graphique en ligne'), ('bar', 'Graphique en barres'), ('stacked_bar', 'Graphique en barres empilées'), ('pie', 'Graphique circulaire'), ('doughnut', 'Graphique en anneau'), ('heatmap', 'Heatmap')], default='bar', max_length=20, verbose_name='Type de graphique')),
                ('display_order', models.IntegerField(default=0, help_text='Plus petit = affiché en premier', verbose_name="Ordre d'affichage")),
                ('size', models.CharField(choices=[('half', 'Demi-largeur'), ('full', 'Pleine largeur')], default='full', max_length=10, verbose_name='Taille')),
                ('query_code', models.TextField(help_text='Code Python pour générer les données. Doit retourner un dict avec "labels" et "datasets".', verbose_name='Code de requête')),
                ('y_axis_label', models.CharField(blank=True, max_length=100, verbose_name='Label axe Y')),
                ('x_axis_label', models.CharField(blank=True, max_length=100, verbose_name='Label axe X')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Configuration de graphique',
                'verbose_name_plural': 'Configurations de graphiques',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
