"""
Django settings for rosa project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-)-4(x9y)29(*2j6v*6=4igarx@-rjnz-z$@#hz57-lb8m%(18@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# CSRF Settings - Important for reverse proxy setup
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:9080,http://127.0.0.1:9080,http://localhost:9000,http://127.0.0.1:9000'
).split(',')


# Application definition

INSTALLED_APPS = [
    'rosa.apps.rosaConfig',  # Configuration principale (admin customization)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local apps
    'users',
    'beneficiaries',
    'volunteers',
    'calendar_app',
    'partners',
    'stock',
    'news',
    'analysis',
    'dons',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'rosa.middleware.AuthenticationMiddleware',  # Notre middleware d'auth
]

ROOT_URLCONF = 'rosa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rosa.context_processors.association_info',  # Infos association
            ],
        },
    },
]

WSGI_APPLICATION = 'rosa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME', 'rosa_db'),
        "USER": os.environ.get('DB_USER', 'rosa_user'),
        "PASSWORD": os.environ.get('DB_PASSWORD', 'rosa_pass'),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internatirosalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.environ.get('STATIC_URL', '/static/')
STATIC_ROOT = os.environ.get('STATIC_ROOT', BASE_DIR / 'static_collected')
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files
MEDIA_URL = os.environ.get('MEDIA_URL', '/media/')
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Mode développement (bypass authentication)
# ATTENTION: Mettre à False pour forcer l'authentification même en développement
DEV_MODE = os.environ.get('DEV_MODE', 'False').lower() in ('true', '1', 't', 'yes')

# Association Configuration
# Nom de l'association affiché dans l'application (navbar, admin, login)
# Par défaut: "ROSA" (Réseau Ouvert de Solidarité et d'Assistance)
# Changez cette valeur pour personnaliser selon votre association
ASSOCIATION_NAME = os.environ.get('ASSOCIATION_NAME', 'ROSA')
ASSOCIATION_FULL_NAME = os.environ.get('ASSOCIATION_FULL_NAME', 'Réseau Ouvert de Solidarité et d\'Assistance')

# Admin URL (for security, use a random path instead of /admin/)
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin')

# HelloAsso Integration Settings
ENABLE_HELLOASSO_INTEGRATION = os.environ.get('ENABLE_HELLOASSO_INTEGRATION', 'True').lower() in ('true', '1', 't', 'yes')
HELLOASSO_API_KEY = os.environ.get('HELLOASSO_API_KEY', 'e68c68ac00654206b8a4057c78dcb285')
HELLOASSO_API_SECRET = os.environ.get('HELLOASSO_API_SECRET', '9G+Zctzo8ZUT0iWaBcJKzTh5YYuHIVbY')
HELLOASSO_ORGANIZATION_SLUG = os.environ.get('HELLOASSO_ORGANIZATION_SLUG', 'association-protestante-d-assistance')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '.claude/django_server.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}